import { Data } from './models/taskInterface';
import { Roles } from './models/enums';
export const DATA: Data[] = [
  {
    id: 1,
    FirstName: 'Christy',
    MiddleName: 'Graze',
    LastName: 'Parrish',
    Email: 'Alex.2331@gmail.com',
    PhoneNumber: '782314564',
    Role: Roles.A,
    Address: 'Street Pork, Los Angeles',
  },
  {
    id: 2,
    FirstName: 'Shelby',
    MiddleName: 'Green',
    LastName: 'Wyatt',
    Email: 'Wyattshelby123@gmail.com',
    PhoneNumber: '734314564',
    Role: Roles.FS,
    Address: 'Downtown, Boston',
  },
  {
    id: 3,
    FirstName: 'Natalie ',
    MiddleName: 'Crystal',
    LastName: 'Vasquez',
    Email: 'Vasquez1996@gmail.com',
    PhoneNumber: '8734314564',
    Role: Roles.S,
    Address: 'Green Avenue, Chicago',
  },
  {
    id: 4,
    FirstName: 'Katherine',
    MiddleName: 'Petrova',
    LastName: 'Peirce',
    Email: 'evil1996@gmail.com',
    PhoneNumber: '9134314564',
    Role: Roles.SA,
    Address: 'White Park, Manhattan',
  },
  {
    id: 5,
    FirstName: 'Daniell ',
    MiddleName: 'Reginald',
    LastName: 'Castellano',
    Email: 'Cast123@gmail.com',
    PhoneNumber: '993431452',
    Role: Roles.BA,
    Address: 'Avenue 16th, Ohio',
  },
];
